version: '3'

services:

  spacebank:
    build: ./SpaceBank
    image: spacebank:latest
    container_name: spacebank
    ports:
      - "8083:8083"

  orders:
    build: ./Orders
    image: orders:latest
    container_name: orders
    ports:
      - "8081:8081"
    environment:
      - MONGODB_CONNSTRING=mongodb://AzureDiamond:hunter2@mongodb

  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
      - MONGO_INITDB_ROOT_PASSWORD=hunter2

  inventory-api:
    build: ./InventoryApi
    ports:
      - "8081:8081"
    expose:
      - 8081

  redis-inventory:
    image: redis:latest
    container_name: redis-Inventory
    ports:
      - "16379:16379"
    expose:
      - 16379

  redis-price:
    image: redis:latest
    container_name: redis-Price
    ports:
      - "6379:6379"
    expose:
      - 6379