version: '3'

services:

  spacebank:
    build: ./SpaceBank
    image: spacebank:latest
    container_name: spacebank
    ports:
      - "8083:8083"

  market:
    build: ./Market
    image: market:latest
    container_name: ${MARKET_HOST}
    ports:
      - ${MARKET_PORT}:${MARKET_PORT}
    environment:
      PRICE_HOST: ${PRICE_HOST}
      PRICE_PORT: ${PRICE_PORT}
      INVENTORY_HOST: ${INVENTORY_HOST}
      INVENTORY_PORT: ${INVENTORY_PORT}
      MARKET_PORT: ${MARKET_PORT}


  orders:
    build: ./Orders
    image: orders:latest
    container_name: orders
    ports:
      - "8082:8082"
      - "3000:3000"
    environment:
      - MONGODB_CONNSTRING=mongodb://AzureDiamond:hunter2@mongodb

  inventory-api:
    build: InventoryApi
    container_name: ${INVENTORY_HOST}
    ports:
      - ${INVENTORY_PORT}:${INVENTORY_PORT}


  price-api:
    build: PriceApi
    container_name: ${PRICE_HOST}
    ports:
      - ${PRICE_PORT}:${PRICE_PORT}

  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
      - MONGO_INITDB_ROOT_PASSWORD=hunter2

  redis-inventory:
    image: redis:latest
    container_name: redis-Inventory
    ports:
      - "6379"

  redis-price:
    image: redis:latest
    container_name: redis-Price
    ports:
      - "6379"