version: '3'

services:

  spacebank:
    build: ./SpaceBank
    image: spacebank:latest
    container_name: spacebank
    ports:
      - "8083:8083"

  market:
    build: ./Market
    image: market:latest
    container_name: market
    ports:
      - "8084:8084"
    expose:
      - 8084

  orders:
    build: ./Orders
    image: orders:latest
    container_name: orders
    ports:
      - "8082:8082"
    environment:
      - MONGODB_CONNSTRING=mongodb://AzureDiamond:hunter2@mongodb

  inventory-api:
    build: InventoryApi
    container_name: inventory-api
    ports:
      - "8081:8081"
    expose:
      - 8081

  price-api:
    build: PriceApi
    container_name: price-api
    ports:
      - "8080:8080"
    expose:
      - 8080

  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
      - MONGO_INITDB_ROOT_PASSWORD=hunter2

  redis-inventory:
    image: redis:latest
    container_name: redis-Inventory
    ports:
      - "6379"

  redis-price:
    image: redis:latest
    container_name: redis-Price
    ports:
      - "6379"