version: '3'

services:

  spacebank:
    build: ./SpaceBank
    image: spacebank:latest
    container_name: spacebank
    network_mode: host
    ports:
      - 8082:8082

  orders:
    build: ./Orders
    image: orders:latest
    container_name: orders
    network_mode: host
    ports:
      - 8081:8081
    environment:
      - MONGODB_CONNSTRING=mongodb://AzureDiamond:hunter2@mongodb

  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
      - MONGO_INITDB_ROOT_PASSWORD=hunter2